-- Read-only virtual forward/inverse transformation; never runs UPDATE.
begin read only; set local statement_timeout='30s';
with current_rules as (select * from public.restaurant_sale_mode_fulfillments where restaurant_id='e8647a29-4971-4629-a5e8-1f00650adfb4'), proposed_rules as (select (jsonb_populate_record(null::public.restaurant_sale_mode_fulfillments, to_jsonb(f) || case when f.id='1d222236-2958-4ada-a5e5-7ce52a52b438' then jsonb_build_object('zone_prefixes',array_replace(f.zone_prefixes,'93008','93000')) when f.id='6434ba6a-707f-41ff-8995-1476dc3c8f10' then jsonb_build_object('zone_prefixes',array_replace(array_replace(array_replace(array_replace(f.zone_prefixes,'92051','92200'),'92009','92270'),'92004','92600'),'93045','93260'),'provider','stuart') else '{}'::jsonb end)).* from public.restaurant_sale_mode_fulfillments f where f.restaurant_id='e8647a29-4971-4629-a5e8-1f00650adfb4'), restored_rules as (select (jsonb_populate_record(null::public.restaurant_sale_mode_fulfillments, to_jsonb(f) || case when f.id='1d222236-2958-4ada-a5e5-7ce52a52b438' then jsonb_build_object('zone_prefixes',array_replace(f.zone_prefixes,'93000','93008')) when f.id='6434ba6a-707f-41ff-8995-1476dc3c8f10' then jsonb_build_object('zone_prefixes',array_replace(array_replace(array_replace(array_replace(f.zone_prefixes,'92200','92051'),'92270','92009'),'92600','92004'),'93260','93045'),'provider','internal') else '{}'::jsonb end)).* from proposed_rules f where f.restaurant_id='e8647a29-4971-4629-a5e8-1f00650adfb4'),
all_rules as (select 'before' phase,f.* from current_rules f union all select 'after',f.* from proposed_rules f),
prefixes as (select phase,id,provider,display_order,pricing_mode,fixed_fee,discount_enabled,discount_threshold,discount_percentage,prefix from all_rules cross join lateral unnest(zone_prefixes) p(prefix) where enabled and not is_fallback and mode_code='delivery'),
codes as (select lpad(n::text,5,'0') postcode from generate_series(0,99999) n),
routes as (select phase,postcode,coalesce(local.id,fallback.id) id,coalesce(local.provider,fallback.provider) provider,coalesce(local.fixed_fee,fallback.fixed_fee) fee from codes cross join (values('before'),('after')) phases(phase)
left join lateral (select p.id,p.provider,p.fixed_fee from prefixes p where p.phase=phases.phase and codes.postcode like p.prefix||'%' order by p.display_order limit 1) local on true
left join lateral (select f.id,f.provider,f.fixed_fee from all_rules f where f.phase=phases.phase and f.enabled and f.is_fallback and f.mode_code='delivery' limit 1) fallback on local.id is null),
changes as (select b.postcode,b.provider before_provider,a.provider after_provider,b.fee before_fee,a.fee after_fee from routes b join routes a on a.postcode=b.postcode and a.phase='after' where b.phase='before' and (b.id,b.provider,b.fee) is distinct from (a.id,a.provider,a.fee)),
prefix_conflicts as (select a.phase,a.id a_id,b.id b_id,a.prefix a_prefix,b.prefix b_prefix from prefixes a join prefixes b on a.phase=b.phase and a.id<b.id and (a.prefix like b.prefix||'%' or b.prefix like a.prefix||'%')),
facts as (select jsonb_build_object('observed_at',now(),'before_hash',(select md5(jsonb_agg(to_jsonb(f) order by f.id)::text) from current_rules f),'after_hash',(select md5(jsonb_agg(to_jsonb(f) order by f.id)::text) from proposed_rules f),'rollback_exact',(select jsonb_agg(to_jsonb(f) order by f.id) from current_rules f)=(select jsonb_agg(to_jsonb(f) order by f.id) from restored_rules f),'changed_rows',(select jsonb_agg(jsonb_build_object('id',b.id,'before',jsonb_build_object('zone_prefixes',b.zone_prefixes,'provider',b.provider),'after',jsonb_build_object('zone_prefixes',a.zone_prefixes,'provider',a.provider))) from current_rules b join proposed_rules a using(id) where to_jsonb(b)<>to_jsonb(a)),'other_fields_unchanged',(select bool_and((to_jsonb(b)-'zone_prefixes'-'provider')=(to_jsonb(a)-'zone_prefixes'-'provider')) from current_rules b join proposed_rules a using(id)),'unrelated_rows_unchanged',(select bool_and(to_jsonb(b)=to_jsonb(a)) from current_rules b join proposed_rules a using(id) where b.id not in ('1d222236-2958-4ada-a5e5-7ce52a52b438','6434ba6a-707f-41ff-8995-1476dc3c8f10')),'overlap_count',(select count(*) from prefix_conflicts),'fallback_count_before',(select count(*) from current_rules where enabled and is_fallback),'fallback_count_after',(select count(*) from proposed_rules where enabled and is_fallback),'postcodes_checked',100000,'routing_changes',(select jsonb_agg(to_jsonb(c) order by postcode) from changes c)) as evidence) select * from facts; commit;
